// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: pkg/api/durupages.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResolvePageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolvePageRequest) Reset() {
	*x = ResolvePageRequest{}
	mi := &file_pkg_api_durupages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolvePageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolvePageRequest) ProtoMessage() {}

func (x *ResolvePageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_durupages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolvePageRequest.ProtoReflect.Descriptor instead.
func (*ResolvePageRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_durupages_proto_rawDescGZIP(), []int{0}
}

func (x *ResolvePageRequest) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

type ResolvePageResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Page  *PageInfo              `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	// cache TTL for the router's resolve cache.
	TtlSeconds    int64 `protobuf:"varint,2,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolvePageResponse) Reset() {
	*x = ResolvePageResponse{}
	mi := &file_pkg_api_durupages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolvePageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolvePageResponse) ProtoMessage() {}

func (x *ResolvePageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_durupages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolvePageResponse.ProtoReflect.Descriptor instead.
func (*ResolvePageResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_durupages_proto_rawDescGZIP(), []int{1}
}

func (x *ResolvePageResponse) GetPage() *PageInfo {
	if x != nil {
		return x.Page
	}
	return nil
}

func (x *ResolvePageResponse) GetTtlSeconds() int64 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

type PageInfo struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	PageId             string                 `protobuf:"bytes,1,opt,name=page_id,json=pageId,proto3" json:"page_id,omitempty"`
	TenantId           string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ActiveDeploymentId string                 `protobuf:"bytes,3,opt,name=active_deployment_id,json=activeDeploymentId,proto3" json:"active_deployment_id,omitempty"`
	HasWorker          bool                   `protobuf:"varint,4,opt,name=has_worker,json=hasWorker,proto3" json:"has_worker,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *PageInfo) Reset() {
	*x = PageInfo{}
	mi := &file_pkg_api_durupages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageInfo) ProtoMessage() {}

func (x *PageInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_durupages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageInfo.ProtoReflect.Descriptor instead.
func (*PageInfo) Descriptor() ([]byte, []int) {
	return file_pkg_api_durupages_proto_rawDescGZIP(), []int{2}
}

func (x *PageInfo) GetPageId() string {
	if x != nil {
		return x.PageId
	}
	return ""
}

func (x *PageInfo) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *PageInfo) GetActiveDeploymentId() string {
	if x != nil {
		return x.ActiveDeploymentId
	}
	return ""
}

func (x *PageInfo) GetHasWorker() bool {
	if x != nil {
		return x.HasWorker
	}
	return false
}

type AcquireSlotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	PageId        string                 `protobuf:"bytes,2,opt,name=page_id,json=pageId,proto3" json:"page_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcquireSlotRequest) Reset() {
	*x = AcquireSlotRequest{}
	mi := &file_pkg_api_durupages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcquireSlotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcquireSlotRequest) ProtoMessage() {}

func (x *AcquireSlotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_durupages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcquireSlotRequest.ProtoReflect.Descriptor instead.
func (*AcquireSlotRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_durupages_proto_rawDescGZIP(), []int{3}
}

func (x *AcquireSlotRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *AcquireSlotRequest) GetPageId() string {
	if x != nil {
		return x.PageId
	}
	return ""
}

type Lease struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	LeaseId string                 `protobuf:"bytes,1,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	// endpoint is the worker shim address (host:port) to proxy to.
	Endpoint string `protobuf:"bytes,2,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	PageId   string `protobuf:"bytes,3,opt,name=page_id,json=pageId,proto3" json:"page_id,omitempty"`
	// deployment_id is the page's active deployment at issuance time; the shim
	// lazy-loads / hot-updates based on this value.
	DeploymentId   string `protobuf:"bytes,4,opt,name=deployment_id,json=deploymentId,proto3" json:"deployment_id,omitempty"`
	DeadlineUnixMs int64  `protobuf:"varint,5,opt,name=deadline_unix_ms,json=deadlineUnixMs,proto3" json:"deadline_unix_ms,omitempty"`
	// request_id correlates usage events and response headers.
	RequestId string `protobuf:"bytes,6,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// signature authenticates the lease towards the worker shim.
	Signature     string `protobuf:"bytes,7,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Lease) Reset() {
	*x = Lease{}
	mi := &file_pkg_api_durupages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Lease) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Lease) ProtoMessage() {}

func (x *Lease) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_durupages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Lease.ProtoReflect.Descriptor instead.
func (*Lease) Descriptor() ([]byte, []int) {
	return file_pkg_api_durupages_proto_rawDescGZIP(), []int{4}
}

func (x *Lease) GetLeaseId() string {
	if x != nil {
		return x.LeaseId
	}
	return ""
}

func (x *Lease) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *Lease) GetPageId() string {
	if x != nil {
		return x.PageId
	}
	return ""
}

func (x *Lease) GetDeploymentId() string {
	if x != nil {
		return x.DeploymentId
	}
	return ""
}

func (x *Lease) GetDeadlineUnixMs() int64 {
	if x != nil {
		return x.DeadlineUnixMs
	}
	return 0
}

func (x *Lease) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *Lease) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

type AcquireSlotEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*AcquireSlotEvent_Queued_
	//	*AcquireSlotEvent_Granted
	//	*AcquireSlotEvent_Timeout_
	Event         isAcquireSlotEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcquireSlotEvent) Reset() {
	*x = AcquireSlotEvent{}
	mi := &file_pkg_api_durupages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcquireSlotEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcquireSlotEvent) ProtoMessage() {}

func (x *AcquireSlotEvent) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_durupages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcquireSlotEvent.ProtoReflect.Descriptor instead.
func (*AcquireSlotEvent) Descriptor() ([]byte, []int) {
	return file_pkg_api_durupages_proto_rawDescGZIP(), []int{5}
}

func (x *AcquireSlotEvent) GetEvent() isAcquireSlotEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *AcquireSlotEvent) GetQueued() *AcquireSlotEvent_Queued {
	if x != nil {
		if x, ok := x.Event.(*AcquireSlotEvent_Queued_); ok {
			return x.Queued
		}
	}
	return nil
}

func (x *AcquireSlotEvent) GetGranted() *Lease {
	if x != nil {
		if x, ok := x.Event.(*AcquireSlotEvent_Granted); ok {
			return x.Granted
		}
	}
	return nil
}

func (x *AcquireSlotEvent) GetTimeout() *AcquireSlotEvent_Timeout {
	if x != nil {
		if x, ok := x.Event.(*AcquireSlotEvent_Timeout_); ok {
			return x.Timeout
		}
	}
	return nil
}

type isAcquireSlotEvent_Event interface {
	isAcquireSlotEvent_Event()
}

type AcquireSlotEvent_Queued_ struct {
	Queued *AcquireSlotEvent_Queued `protobuf:"bytes,1,opt,name=queued,proto3,oneof"`
}

type AcquireSlotEvent_Granted struct {
	Granted *Lease `protobuf:"bytes,2,opt,name=granted,proto3,oneof"`
}

type AcquireSlotEvent_Timeout_ struct {
	Timeout *AcquireSlotEvent_Timeout `protobuf:"bytes,3,opt,name=timeout,proto3,oneof"`
}

func (*AcquireSlotEvent_Queued_) isAcquireSlotEvent_Event() {}

func (*AcquireSlotEvent_Granted) isAcquireSlotEvent_Event() {}

func (*AcquireSlotEvent_Timeout_) isAcquireSlotEvent_Event() {}

type ReleaseSlotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LeaseId       string                 `protobuf:"bytes,1,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseSlotRequest) Reset() {
	*x = ReleaseSlotRequest{}
	mi := &file_pkg_api_durupages_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseSlotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseSlotRequest) ProtoMessage() {}

func (x *ReleaseSlotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_durupages_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseSlotRequest.ProtoReflect.Descriptor instead.
func (*ReleaseSlotRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_durupages_proto_rawDescGZIP(), []int{6}
}

func (x *ReleaseSlotRequest) GetLeaseId() string {
	if x != nil {
		return x.LeaseId
	}
	return ""
}

type ReleaseSlotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseSlotResponse) Reset() {
	*x = ReleaseSlotResponse{}
	mi := &file_pkg_api_durupages_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseSlotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseSlotResponse) ProtoMessage() {}

func (x *ReleaseSlotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_durupages_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseSlotResponse.ProtoReflect.Descriptor instead.
func (*ReleaseSlotResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_durupages_proto_rawDescGZIP(), []int{7}
}

type GetPageConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageId        string                 `protobuf:"bytes,1,opt,name=page_id,json=pageId,proto3" json:"page_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPageConfigRequest) Reset() {
	*x = GetPageConfigRequest{}
	mi := &file_pkg_api_durupages_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPageConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPageConfigRequest) ProtoMessage() {}

func (x *GetPageConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_durupages_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPageConfigRequest.ProtoReflect.Descriptor instead.
func (*GetPageConfigRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_durupages_proto_rawDescGZIP(), []int{8}
}

func (x *GetPageConfigRequest) GetPageId() string {
	if x != nil {
		return x.PageId
	}
	return ""
}

type GetPageConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Env           map[string]string      `protobuf:"bytes,1,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Secret        map[string]string      `protobuf:"bytes,2,rep,name=secret,proto3" json:"secret,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPageConfigResponse) Reset() {
	*x = GetPageConfigResponse{}
	mi := &file_pkg_api_durupages_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPageConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPageConfigResponse) ProtoMessage() {}

func (x *GetPageConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_durupages_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPageConfigResponse.ProtoReflect.Descriptor instead.
func (*GetPageConfigResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_durupages_proto_rawDescGZIP(), []int{9}
}

func (x *GetPageConfigResponse) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *GetPageConfigResponse) GetSecret() map[string]string {
	if x != nil {
		return x.Secret
	}
	return nil
}

type RegisterRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	TenantId string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	PodName  string                 `protobuf:"bytes,2,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	// endpoint the shim serves requests on (host:port).
	Endpoint      string `protobuf:"bytes,3,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_pkg_api_durupages_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_durupages_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_durupages_proto_rawDescGZIP(), []int{10}
}

func (x *RegisterRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *RegisterRequest) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

func (x *RegisterRequest) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

type RegisterResponse struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	HeartbeatIntervalSeconds int64                  `protobuf:"varint,1,opt,name=heartbeat_interval_seconds,json=heartbeatIntervalSeconds,proto3" json:"heartbeat_interval_seconds,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_pkg_api_durupages_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_durupages_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_durupages_proto_rawDescGZIP(), []int{11}
}

func (x *RegisterResponse) GetHeartbeatIntervalSeconds() int64 {
	if x != nil {
		return x.HeartbeatIntervalSeconds
	}
	return 0
}

type LoadedPage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageId        string                 `protobuf:"bytes,1,opt,name=page_id,json=pageId,proto3" json:"page_id,omitempty"`
	DeploymentId  string                 `protobuf:"bytes,2,opt,name=deployment_id,json=deploymentId,proto3" json:"deployment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadedPage) Reset() {
	*x = LoadedPage{}
	mi := &file_pkg_api_durupages_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadedPage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadedPage) ProtoMessage() {}

func (x *LoadedPage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_durupages_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadedPage.ProtoReflect.Descriptor instead.
func (*LoadedPage) Descriptor() ([]byte, []int) {
	return file_pkg_api_durupages_proto_rawDescGZIP(), []int{12}
}

func (x *LoadedPage) GetPageId() string {
	if x != nil {
		return x.PageId
	}
	return ""
}

func (x *LoadedPage) GetDeploymentId() string {
	if x != nil {
		return x.DeploymentId
	}
	return ""
}

type HeartbeatRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// state: "ready" | "serving" | "idle" | "draining".
	State         string        `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	InFlight      int64         `protobuf:"varint,2,opt,name=in_flight,json=inFlight,proto3" json:"in_flight,omitempty"`
	LoadedPages   []*LoadedPage `protobuf:"bytes,3,rep,name=loaded_pages,json=loadedPages,proto3" json:"loaded_pages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_pkg_api_durupages_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_durupages_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_durupages_proto_rawDescGZIP(), []int{13}
}

func (x *HeartbeatRequest) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *HeartbeatRequest) GetInFlight() int64 {
	if x != nil {
		return x.InFlight
	}
	return 0
}

func (x *HeartbeatRequest) GetLoadedPages() []*LoadedPage {
	if x != nil {
		return x.LoadedPages
	}
	return nil
}

type HeartbeatResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// drain instructs the shim to stop accepting leases and finish in-flight.
	Drain bool `protobuf:"varint,1,opt,name=drain,proto3" json:"drain,omitempty"`
	// renewed_jwt replaces the worker JWT before expiry (empty = keep).
	RenewedJwt    string `protobuf:"bytes,2,opt,name=renewed_jwt,json=renewedJwt,proto3" json:"renewed_jwt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_pkg_api_durupages_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_durupages_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_durupages_proto_rawDescGZIP(), []int{14}
}

func (x *HeartbeatResponse) GetDrain() bool {
	if x != nil {
		return x.Drain
	}
	return false
}

func (x *HeartbeatResponse) GetRenewedJwt() string {
	if x != nil {
		return x.RenewedJwt
	}
	return ""
}

type IngestBatch struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	BatchId int64                  `protobuf:"varint,1,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	// Events serialized with the pkg/usage JSON schema (single source of truth
	// shared with the pod-log JSON Lines format).
	RequestUsageJson [][]byte `protobuf:"bytes,2,rep,name=request_usage_json,json=requestUsageJson,proto3" json:"request_usage_json,omitempty"`
	StaticAccessJson [][]byte `protobuf:"bytes,3,rep,name=static_access_json,json=staticAccessJson,proto3" json:"static_access_json,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *IngestBatch) Reset() {
	*x = IngestBatch{}
	mi := &file_pkg_api_durupages_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestBatch) ProtoMessage() {}

func (x *IngestBatch) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_durupages_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestBatch.ProtoReflect.Descriptor instead.
func (*IngestBatch) Descriptor() ([]byte, []int) {
	return file_pkg_api_durupages_proto_rawDescGZIP(), []int{15}
}

func (x *IngestBatch) GetBatchId() int64 {
	if x != nil {
		return x.BatchId
	}
	return 0
}

func (x *IngestBatch) GetRequestUsageJson() [][]byte {
	if x != nil {
		return x.RequestUsageJson
	}
	return nil
}

func (x *IngestBatch) GetStaticAccessJson() [][]byte {
	if x != nil {
		return x.StaticAccessJson
	}
	return nil
}

type IngestAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BatchId       int64                  `protobuf:"varint,1,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestAck) Reset() {
	*x = IngestAck{}
	mi := &file_pkg_api_durupages_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestAck) ProtoMessage() {}

func (x *IngestAck) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_durupages_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestAck.ProtoReflect.Descriptor instead.
func (*IngestAck) Descriptor() ([]byte, []int) {
	return file_pkg_api_durupages_proto_rawDescGZIP(), []int{16}
}

func (x *IngestAck) GetBatchId() int64 {
	if x != nil {
		return x.BatchId
	}
	return 0
}

type AcquireSlotEvent_Queued struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Position      int64                  `protobuf:"varint,1,opt,name=position,proto3" json:"position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcquireSlotEvent_Queued) Reset() {
	*x = AcquireSlotEvent_Queued{}
	mi := &file_pkg_api_durupages_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcquireSlotEvent_Queued) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcquireSlotEvent_Queued) ProtoMessage() {}

func (x *AcquireSlotEvent_Queued) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_durupages_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcquireSlotEvent_Queued.ProtoReflect.Descriptor instead.
func (*AcquireSlotEvent_Queued) Descriptor() ([]byte, []int) {
	return file_pkg_api_durupages_proto_rawDescGZIP(), []int{5, 0}
}

func (x *AcquireSlotEvent_Queued) GetPosition() int64 {
	if x != nil {
		return x.Position
	}
	return 0
}

type AcquireSlotEvent_Timeout struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcquireSlotEvent_Timeout) Reset() {
	*x = AcquireSlotEvent_Timeout{}
	mi := &file_pkg_api_durupages_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcquireSlotEvent_Timeout) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcquireSlotEvent_Timeout) ProtoMessage() {}

func (x *AcquireSlotEvent_Timeout) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_durupages_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcquireSlotEvent_Timeout.ProtoReflect.Descriptor instead.
func (*AcquireSlotEvent_Timeout) Descriptor() ([]byte, []int) {
	return file_pkg_api_durupages_proto_rawDescGZIP(), []int{5, 1}
}

var File_pkg_api_durupages_proto protoreflect.FileDescriptor

const file_pkg_api_durupages_proto_rawDesc = "" +
	"\n" +
	"\x17pkg/api/durupages.proto\x12\fdurupages.v1\"(\n" +
	"\x12ResolvePageRequest\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\"b\n" +
	"\x13ResolvePageResponse\x12*\n" +
	"\x04page\x18\x01 \x01(\v2\x16.durupages.v1.PageInfoR\x04page\x12\x1f\n" +
	"\vttl_seconds\x18\x02 \x01(\x03R\n" +
	"ttlSeconds\"\x91\x01\n" +
	"\bPageInfo\x12\x17\n" +
	"\apage_id\x18\x01 \x01(\tR\x06pageId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x120\n" +
	"\x14active_deployment_id\x18\x03 \x01(\tR\x12activeDeploymentId\x12\x1d\n" +
	"\n" +
	"has_worker\x18\x04 \x01(\bR\thasWorker\"J\n" +
	"\x12AcquireSlotRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x17\n" +
	"\apage_id\x18\x02 \x01(\tR\x06pageId\"\xe3\x01\n" +
	"\x05Lease\x12\x19\n" +
	"\blease_id\x18\x01 \x01(\tR\aleaseId\x12\x1a\n" +
	"\bendpoint\x18\x02 \x01(\tR\bendpoint\x12\x17\n" +
	"\apage_id\x18\x03 \x01(\tR\x06pageId\x12#\n" +
	"\rdeployment_id\x18\x04 \x01(\tR\fdeploymentId\x12(\n" +
	"\x10deadline_unix_ms\x18\x05 \x01(\x03R\x0edeadlineUnixMs\x12\x1d\n" +
	"\n" +
	"request_id\x18\x06 \x01(\tR\trequestId\x12\x1c\n" +
	"\tsignature\x18\a \x01(\tR\tsignature\"\x82\x02\n" +
	"\x10AcquireSlotEvent\x12?\n" +
	"\x06queued\x18\x01 \x01(\v2%.durupages.v1.AcquireSlotEvent.QueuedH\x00R\x06queued\x12/\n" +
	"\agranted\x18\x02 \x01(\v2\x13.durupages.v1.LeaseH\x00R\agranted\x12B\n" +
	"\atimeout\x18\x03 \x01(\v2&.durupages.v1.AcquireSlotEvent.TimeoutH\x00R\atimeout\x1a$\n" +
	"\x06Queued\x12\x1a\n" +
	"\bposition\x18\x01 \x01(\x03R\bposition\x1a\t\n" +
	"\aTimeoutB\a\n" +
	"\x05event\"/\n" +
	"\x12ReleaseSlotRequest\x12\x19\n" +
	"\blease_id\x18\x01 \x01(\tR\aleaseId\"\x15\n" +
	"\x13ReleaseSlotResponse\"/\n" +
	"\x14GetPageConfigRequest\x12\x17\n" +
	"\apage_id\x18\x01 \x01(\tR\x06pageId\"\x93\x02\n" +
	"\x15GetPageConfigResponse\x12>\n" +
	"\x03env\x18\x01 \x03(\v2,.durupages.v1.GetPageConfigResponse.EnvEntryR\x03env\x12G\n" +
	"\x06secret\x18\x02 \x03(\v2/.durupages.v1.GetPageConfigResponse.SecretEntryR\x06secret\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a9\n" +
	"\vSecretEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"e\n" +
	"\x0fRegisterRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x19\n" +
	"\bpod_name\x18\x02 \x01(\tR\apodName\x12\x1a\n" +
	"\bendpoint\x18\x03 \x01(\tR\bendpoint\"P\n" +
	"\x10RegisterResponse\x12<\n" +
	"\x1aheartbeat_interval_seconds\x18\x01 \x01(\x03R\x18heartbeatIntervalSeconds\"J\n" +
	"\n" +
	"LoadedPage\x12\x17\n" +
	"\apage_id\x18\x01 \x01(\tR\x06pageId\x12#\n" +
	"\rdeployment_id\x18\x02 \x01(\tR\fdeploymentId\"\x82\x01\n" +
	"\x10HeartbeatRequest\x12\x14\n" +
	"\x05state\x18\x01 \x01(\tR\x05state\x12\x1b\n" +
	"\tin_flight\x18\x02 \x01(\x03R\binFlight\x12;\n" +
	"\floaded_pages\x18\x03 \x03(\v2\x18.durupages.v1.LoadedPageR\vloadedPages\"J\n" +
	"\x11HeartbeatResponse\x12\x14\n" +
	"\x05drain\x18\x01 \x01(\bR\x05drain\x12\x1f\n" +
	"\vrenewed_jwt\x18\x02 \x01(\tR\n" +
	"renewedJwt\"\x84\x01\n" +
	"\vIngestBatch\x12\x19\n" +
	"\bbatch_id\x18\x01 \x01(\x03R\abatchId\x12,\n" +
	"\x12request_usage_json\x18\x02 \x03(\fR\x10requestUsageJson\x12,\n" +
	"\x12static_access_json\x18\x03 \x03(\fR\x10staticAccessJson\"&\n" +
	"\tIngestAck\x12\x19\n" +
	"\bbatch_id\x18\x01 \x01(\x03R\abatchId2\x8a\x02\n" +
	"\rRouterService\x12R\n" +
	"\vResolvePage\x12 .durupages.v1.ResolvePageRequest\x1a!.durupages.v1.ResolvePageResponse\x12Q\n" +
	"\vAcquireSlot\x12 .durupages.v1.AcquireSlotRequest\x1a\x1e.durupages.v1.AcquireSlotEvent0\x01\x12R\n" +
	"\vReleaseSlot\x12 .durupages.v1.ReleaseSlotRequest\x1a!.durupages.v1.ReleaseSlotResponse2\x86\x02\n" +
	"\rWorkerService\x12I\n" +
	"\bRegister\x12\x1d.durupages.v1.RegisterRequest\x1a\x1e.durupages.v1.RegisterResponse\x12P\n" +
	"\tHeartbeat\x12\x1e.durupages.v1.HeartbeatRequest\x1a\x1f.durupages.v1.HeartbeatResponse(\x010\x01\x12X\n" +
	"\rGetPageConfig\x12\".durupages.v1.GetPageConfigRequest\x1a#.durupages.v1.GetPageConfigResponse2N\n" +
	"\n" +
	"LogService\x12@\n" +
	"\x06Ingest\x12\x19.durupages.v1.IngestBatch\x1a\x17.durupages.v1.IngestAck(\x010\x01B,Z*github.com/durupages/durupages/pkg/api;apib\x06proto3"

var (
	file_pkg_api_durupages_proto_rawDescOnce sync.Once
	file_pkg_api_durupages_proto_rawDescData []byte
)

func file_pkg_api_durupages_proto_rawDescGZIP() []byte {
	file_pkg_api_durupages_proto_rawDescOnce.Do(func() {
		file_pkg_api_durupages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_api_durupages_proto_rawDesc), len(file_pkg_api_durupages_proto_rawDesc)))
	})
	return file_pkg_api_durupages_proto_rawDescData
}

var file_pkg_api_durupages_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_pkg_api_durupages_proto_goTypes = []any{
	(*ResolvePageRequest)(nil),       // 0: durupages.v1.ResolvePageRequest
	(*ResolvePageResponse)(nil),      // 1: durupages.v1.ResolvePageResponse
	(*PageInfo)(nil),                 // 2: durupages.v1.PageInfo
	(*AcquireSlotRequest)(nil),       // 3: durupages.v1.AcquireSlotRequest
	(*Lease)(nil),                    // 4: durupages.v1.Lease
	(*AcquireSlotEvent)(nil),         // 5: durupages.v1.AcquireSlotEvent
	(*ReleaseSlotRequest)(nil),       // 6: durupages.v1.ReleaseSlotRequest
	(*ReleaseSlotResponse)(nil),      // 7: durupages.v1.ReleaseSlotResponse
	(*GetPageConfigRequest)(nil),     // 8: durupages.v1.GetPageConfigRequest
	(*GetPageConfigResponse)(nil),    // 9: durupages.v1.GetPageConfigResponse
	(*RegisterRequest)(nil),          // 10: durupages.v1.RegisterRequest
	(*RegisterResponse)(nil),         // 11: durupages.v1.RegisterResponse
	(*LoadedPage)(nil),               // 12: durupages.v1.LoadedPage
	(*HeartbeatRequest)(nil),         // 13: durupages.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil),        // 14: durupages.v1.HeartbeatResponse
	(*IngestBatch)(nil),              // 15: durupages.v1.IngestBatch
	(*IngestAck)(nil),                // 16: durupages.v1.IngestAck
	(*AcquireSlotEvent_Queued)(nil),  // 17: durupages.v1.AcquireSlotEvent.Queued
	(*AcquireSlotEvent_Timeout)(nil), // 18: durupages.v1.AcquireSlotEvent.Timeout
	nil,                              // 19: durupages.v1.GetPageConfigResponse.EnvEntry
	nil,                              // 20: durupages.v1.GetPageConfigResponse.SecretEntry
}
var file_pkg_api_durupages_proto_depIdxs = []int32{
	2,  // 0: durupages.v1.ResolvePageResponse.page:type_name -> durupages.v1.PageInfo
	17, // 1: durupages.v1.AcquireSlotEvent.queued:type_name -> durupages.v1.AcquireSlotEvent.Queued
	4,  // 2: durupages.v1.AcquireSlotEvent.granted:type_name -> durupages.v1.Lease
	18, // 3: durupages.v1.AcquireSlotEvent.timeout:type_name -> durupages.v1.AcquireSlotEvent.Timeout
	19, // 4: durupages.v1.GetPageConfigResponse.env:type_name -> durupages.v1.GetPageConfigResponse.EnvEntry
	20, // 5: durupages.v1.GetPageConfigResponse.secret:type_name -> durupages.v1.GetPageConfigResponse.SecretEntry
	12, // 6: durupages.v1.HeartbeatRequest.loaded_pages:type_name -> durupages.v1.LoadedPage
	0,  // 7: durupages.v1.RouterService.ResolvePage:input_type -> durupages.v1.ResolvePageRequest
	3,  // 8: durupages.v1.RouterService.AcquireSlot:input_type -> durupages.v1.AcquireSlotRequest
	6,  // 9: durupages.v1.RouterService.ReleaseSlot:input_type -> durupages.v1.ReleaseSlotRequest
	10, // 10: durupages.v1.WorkerService.Register:input_type -> durupages.v1.RegisterRequest
	13, // 11: durupages.v1.WorkerService.Heartbeat:input_type -> durupages.v1.HeartbeatRequest
	8,  // 12: durupages.v1.WorkerService.GetPageConfig:input_type -> durupages.v1.GetPageConfigRequest
	15, // 13: durupages.v1.LogService.Ingest:input_type -> durupages.v1.IngestBatch
	1,  // 14: durupages.v1.RouterService.ResolvePage:output_type -> durupages.v1.ResolvePageResponse
	5,  // 15: durupages.v1.RouterService.AcquireSlot:output_type -> durupages.v1.AcquireSlotEvent
	7,  // 16: durupages.v1.RouterService.ReleaseSlot:output_type -> durupages.v1.ReleaseSlotResponse
	11, // 17: durupages.v1.WorkerService.Register:output_type -> durupages.v1.RegisterResponse
	14, // 18: durupages.v1.WorkerService.Heartbeat:output_type -> durupages.v1.HeartbeatResponse
	9,  // 19: durupages.v1.WorkerService.GetPageConfig:output_type -> durupages.v1.GetPageConfigResponse
	16, // 20: durupages.v1.LogService.Ingest:output_type -> durupages.v1.IngestAck
	14, // [14:21] is the sub-list for method output_type
	7,  // [7:14] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_pkg_api_durupages_proto_init() }
func file_pkg_api_durupages_proto_init() {
	if File_pkg_api_durupages_proto != nil {
		return
	}
	file_pkg_api_durupages_proto_msgTypes[5].OneofWrappers = []any{
		(*AcquireSlotEvent_Queued_)(nil),
		(*AcquireSlotEvent_Granted)(nil),
		(*AcquireSlotEvent_Timeout_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_api_durupages_proto_rawDesc), len(file_pkg_api_durupages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_pkg_api_durupages_proto_goTypes,
		DependencyIndexes: file_pkg_api_durupages_proto_depIdxs,
		MessageInfos:      file_pkg_api_durupages_proto_msgTypes,
	}.Build()
	File_pkg_api_durupages_proto = out.File
	file_pkg_api_durupages_proto_goTypes = nil
	file_pkg_api_durupages_proto_depIdxs = nil
}
