# Copyright 2026 JC-Lab
# SPDX-License-Identifier: EPL-2.0

{{- if not .Values.postgres.existingSecret }}
{{- if empty .Values.postgres.dsn }}
{{- fail "\n\ndurupages: PostgreSQL connection is required.\nSet postgres.existingSecret (+ postgres.existingSecretKey) OR postgres.dsn.\n" }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "durupages.postgresSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "durupages.labels" . | nindent 4 }}
type: Opaque
stringData:
  dsn: {{ .Values.postgres.dsn | quote }}
{{- end }}
